### ISSUE TITLE
Definitions invisible in Dark Mode

### ISSUE THREAD

**Issue by dj0nes** [ponychicken/WebsterParser#5]
When using the given .dictionary file with dark mode enabled, only the headers are visible.

Thankfully, there is a simple fix!

Edit this file `Webster’s 1913.dictionary/Contents/DefaultStyle.css`

and add

```css
@media (prefers-dark-interface) {
  html {
    -apple-color-filter: apple-invert-lightness();
  }
  a {
    -apple-color-filter: none;
    color: -webkit-link;
  }
  img {
    filter: invert(100%);
  }
}
```

anywhere as its own top-level block.

Thanks to user Garland in the comments from [this blog post](https://eclecticlight.co/2018/09/29/mojaves-dictionary-where-light-and-dark-modes-collide/#comment-20470).

**Comment by cormacrelf** [comment]
The resulting background is a bit different from the system dictionaries. This gets it right:

```css
html {
  /* There is a style="background: white" on the html element we have to beat */
  background: none !important;
}

@media (prefers-dark-interface) {
  .hw {
    /* blue is more readable on the dark background than maroon */
    color: -webkit-link;
  }
  img {
    filter: invert(100%);
  }
}
```
